### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Streppel** [jasonlvhit/gocron#121]
As reported by @preslavrachev on https://github.com/jasonlvhit/gocron/issues/117#issuecomment-548971950, the tests 

- TestDaily
- TestWeekdayAferToday
- TestWeekdayAt

appear to be failing at master branch. To be investigated and fixed.

**Comment by Streppel** [comment]
Unfortunately I could not reproduce locally under the master branch

<img width="727" alt="image" src="https://user-images.githubusercontent.com/2300328/68089629-99eca000-fe49-11e9-84df-d66abfcc01aa.png">

**Comment by preslavrachev** [comment]
As of today's run, me neither. But those were apparent a few days back, which is an indication that we still need to keep an eye. @Streppel please, open up a ticket for setting up a Travis CI test automation. You can assign that to me. I have quite a bit of CI experience, so I could definitely help there.

I will be quite busy the next couple of days, but I can get it set up by the end of the week.

**Comment by Streppel** [comment]
@preslavrachev that's amazing! And yes, this kind of failures tend occur on edge cases like end of months etc because our tests are deterministic, but [there is an issue open for that](https://github.com/jasonlvhit/gocron/issues/88) so we will take care of that soon. While you do that, I'll work on the conflicts of merging [this PR](https://github.com/jasonlvhit/gocron/pull/60) which is a game changer but was never merged before, and then we can have a fresh look on the tests
