### ISSUE TITLE
"Sleep until next run time if we wake up too early" breaks RunAll

### ISSUE THREAD

**Issue by bir** [jasonlvhit/gocron#135]
This commit:
https://github.com/jasonlvhit/gocron/commit/9b1e2c8fb35cdd55baca0360076805108921dcd0

Causes RunAll commands to hang until next run time, which defeats the purpose of RunAll. 
// RunAll run all jobs regardless if they are scheduled to run or not

 I have a job that is run at startup and then once per hour afterward.  This commit causes it to sleep for a painfully long time.  Not sure what the patch was meant to fix but it certainly breaks the RunAll contract.

**Comment by kamko** [comment]
Yes, just hit the same issue.

**Comment by bir** [comment]
@kamko I fixed by setting the go.mod require line to the previous version:

    github.com/jasonlvhit/gocron v0.0.0-20191125235832-30e323a962ed

**Comment by kamko** [comment]
thanks, altough as i had only one job i simply ran it explicitly.

**Comment by Streppel** [comment]
@bir this is the PR for the commit https://github.com/jasonlvhit/gocron/pull/133. I didn't know about these issues so I'll be reverting these changes. Thanks for shouting out!
