### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by piotrkochan** [jasonlvhit/gocron#140]
The is a lot of old Issues, `s.Every(1).Weekday(time.Monday)` does not work

**Comment by Streppel** [comment]
It is, @piotrkochan. It was not very crowded as as of few months ago, but a few folks (myself include) got together to invest their own time on cleaning old issues. I didn't know of this weekday issue, I'll try to take a look into it this weekend. You are more than welcome to collaborate, too! Just send in a pull request (backed with tests) so we can review it and merge it!
