### ISSUE TITLE
Small size job executed twice occasionally

### ISSUE THREAD

**Issue by hangpark** [jasonlvhit/gocron#142]
## Description

Sometimes a small size job (i.e. a job with very short execution time) is executed twice in sequential ticks.

## Reproducing Steps

1. Go to https://github.com/jasonlvhit/gocron/blob/98b59b546dee5e226421a00e3cfcb6223bdc839e/gocron_test.go#L36
2. Increase `numberOfIterations` like 20 (10x times)
3. Run `TestSeconds()`
4. Below is my failure logs:
<details><summary>Failure Logs</summary>

```
GOROOT=/usr/local/Cellar/go/1.13.1/libexec #gosetup
GOPATH=/Users/hangpark/Projects/go #gosetup
/usr/local/Cellar/go/1.13.1/libexec/bin/go test -c -o /private/var/folders/0s/mw5ww6q52t5fmc1s9nsn_01w0000gp/T/___TestSeconds_in_github_com_jasonlvhit_gocron github.com/jasonlvhit/gocron #gosetup
/usr/local/Cellar/go/1.13.1/libexec/bin/go tool test2json -t /private/var/folders/0s/mw5ww6q52t5fmc1s9nsn_01w0000gp/T/___TestSeconds_in_github_com_jasonlvhit_gocron -test.v -test.run ^TestSeconds$ #gosetup
=== RUN   TestSeconds
--- FAIL: TestSeconds (32.00s)
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 1
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations


Expected :2
Actual   :1
<Click to see difference>


FAIL

Process finished with exit code 1
```

</details>

## Why?

For each tick, the scheduler calculates jobs to run at that tick by calling `getRunnableJobs()`. This  method is just call `job.shouldRun()` for all registered jobs, which is:
https://github.com/jasonlvhit/gocron/blob/98b59b546dee5e226421a00e3cfcb6223bdc839e/gocron.go#L102-L104

And then the scheduler runs runnable jobs (`job.run()`). After each runnable job is executed, that is at the end of `job.run()`, a job is rescheduled by
https://github.com/jasonlvhit/gocron/blob/98b59b546dee5e226421a00e3cfcb6223bdc839e/gocron.go#L128

But, in `job.run()`, **if current time is BEFORE next running time, it skips rescheduling.**
https://github.com/jasonlvhit/gocron/blob/98b59b546dee5e226421a00e3cfcb6223bdc839e/gocron.go#L291-L293

Now, let me illustrate a sample case:

1. Job named `job` has `nextRun` at `2020-01-01T00:00:00.900Z`
2. Tick is started at `2020-01-01T00:00:00.000Z`
3. `job` is appended into runnable jobs **<----- (A)**
4. Scheduler executes `job`
5. `job` has been executed very fast, current time: `2020-01-01T00:00:00.100Z`
6. `job` should be rescheduled
7. But `job.nextRun` is after the current time. **<------ (B)**
8. On next second, the next tick append `job` into runnable jobs
9. `job` is executed TWICE!

The problem is, **(A)** compares `nextRun` with the current time by using "seconds" while **(B)** compares by using "nanoseconds". In other words, `time.Now().Unix() >= j.nextRun.Unix()` and `j.nextRun.After(now)` have different degrees of precision.

## Does this fix?

Is this bug fixed if we change `time.Now().Unix() >= j.nextRun.Unix()` to `time.Now.After(j.nextRun)`? Yeah, probabily... but with this fix may cause the another bug.

Since every function has at least nanosecond execution time, `job := sched.Every(2).Seconds()` is sometimes executed in 3 secs, not 2. See below test results:

<details><summary>After applying ns precision</summary>

```
=== RUN   TestSeconds
--- FAIL: TestSeconds (48.00s)
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations
    gocron_test.go:53: 
        	Error Trace:	gocron_test.go:53
        	            				gocron_test.go:30
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestSeconds
        	Messages:   	Duration between tasks does not correspond to expectations


Expected :2
Actual   :3
<Click to see difference>


FAIL

Process finished with exit code 1
```

</details>

## TODO

Can changing tick interval more finely be the solution?
Or can we just delete below code? https://github.com/jasonlvhit/gocron/blob/98b59b546dee5e226421a00e3cfcb6223bdc839e/gocron.go#L291-L293

Anyway, this bug seems to be critical for cases which are non-idempotent jobs (with fast execution time).

**Comment by Streppel** [comment]
Amazing description, thank you for taking the time to write this! The ```.Unix()``` approach was chosen because of the nanoseconds issue indeed as you pointed here. We need to review our scheduling logic indeed. Will take a look into it, as well as hope someone else take a look into this too (the more eyes the better)

**Comment by LipingMao** [comment]
I get the same issue with the sample code in README.md .

I think maybe we can delete the check:
```
	if j.nextRun.After(now) {
		return
	}
```

Any reason to check this when we scheduleNextRun?

**Comment by avasani** [comment]
Do we know the fix for this issue?

**Comment by Streppel** [comment]
@avasani have you tried deleting the code to see if it fixes it as well? We are working on a fix on our fork https://github.com/go-co-op/gocron/pull/23 that will be applied here as well when we finish it, since this is critical. We are testing the removal of the code.
