### ISSUE TITLE
Consider the location implementation

### ISSUE THREAD

**Issue by JohnRoesler** [jasonlvhit/gocron#148]
I'm not sure we need the global `loc` var as the scheduler itself stores location and the scheduler runs jobs. 

Is there a need to have jobs have a separate location? Would someone ever run a scheduler in say UTC and then want to trigger a job at say 10:00AM UTC +2?

To solve this you could create multiple schedulers for the different time zones.

**Comment by Streppel** [comment]
I agree... We should consider timezones by schedulers only. Time no clean up this codebase :) I'm preparing another PR soon
