### ISSUE TITLE
Every second Thursday

### ISSUE THREAD

**Issue by mlanin** [jasonlvhit/gocron#154]
I need a task to be fired every second Thursday. I tried to do like this:
`gocron.Every(2).Thursday().At("08:00").Do(taskHandler)` but got panic `interval must be 1`.

Is it even possible to do what I need?

**Comment by Streppel** [comment]
This is currently not possible, unfortunately, but that's a nice catch. We'll implement it. I'll open an issue for this on https://github.com/go-co-op/gocron
