### ISSUE TITLE
getRunnableJobs runnableJobs is not needed

### ISSUE THREAD

**Issue by scythefly** [jasonlvhit/gocron#161]
```
// Get the current runnable jobs, which shouldRun is True
func (s *Scheduler) getRunnableJobs() (runningJobs [MAXJOBNUM]*Job, n int) {
	runnableJobs := [MAXJOBNUM]*Job{}
	n = 0
        // ...
        return runnableJobs, n
```

if  I make many schedulers with a few jobs in every single s  , alloc array with MAXJOBNUM is a waste.

```
// Get the current runnable jobs, which shouldRun is True
func (s *Scheduler) getRunnableJobs() []*Job {
	var runnableJobs []*Job
	sort.Sort(s)
	for i := 0; i < s.size; i++ {
		if s.jobs[i].shouldRun() {
			runnableJobs = append(runnableJobs, s.jobs[i])
		} else {
			break
		}
	}
	return runnableJobs
}

...


// RunPending runs all the jobs that are scheduled to run.
func (s *Scheduler) RunPending() {
	runnableJobs := s.getRunnableJobs()

	if runnableJobs != nil {
		for _, j := range runnableJobs {
			go j.run()
			j.lastRun = time.Now()
			j.scheduleNextRun()
		}
	}
}
```

**Comment by arjunmahishi** [comment]
Hey @scythefly, that's a valid point. But this repo is now stale. We have moved the development of this project to a [new repo](https://github.com/go-co-op/gocron). There we have [fixed this](https://github.com/go-co-op/gocron/blob/25952fd63f85ccebffad02af43df88621a0982b8/scheduler.go#L126) and a few other bugs. We have also added a couple of new features. You can perhaps [check it out](https://github.com/go-co-op/gocron).

Thanks for reaching out! :)

**Comment by scythefly** [comment]
oh oh, thanks a lot!
