### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [jasonlvhit/gocron#162]
I found that this project already [supports Go modules](https://github.com/jasonlvhit/gocron/blob/master/go.mod). But sadly, the [tags](https://github.com/jasonlvhit/gocron/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/jasonlvhit/gocron v0.0.0-20200423141508-ab84337f7963
```
Else the mod file shows something like `github.com/jasonlvhit/gocron v0.0.0-20200423141508-ab84337f7963` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by KateGo520** [comment]
@Streppel  @Arjunmahishi  Could you help me review this issue? Thx :p

**Comment by Streppel** [comment]
Hi @KateGo520! Absolutely, we can fix this here. Be aware, though, that we migrated to a new repo linked in the readme and we are working collectively over there, be sure to check it out!

**Comment by Streppel** [comment]
Updated semver :-)

**Comment by KateGo520** [comment]
@Streppel  OK, I see the new link. Thank you!
