### ISSUE TITLE
Schedule task every X hours from a date in the past

### ISSUE THREAD

**Issue by antoniocapizzi95** [jasonlvhit/gocron#166]
Hello, I'm using this method to schedule a task:

```
// Begin job at a specific date/time
t := time.Date(2019, time.November, 10, 15, 0, 0, 0, time.Local)
gocron.Every(1).Hour().From(&t).Do(task)
```

My aim is to schedule a task every 3 hours from midnight, but it seems that at startup it starts counting from the script execution time. My code is the below:
```
today := time.Now()
t := time.Date(today.Year(), today.Month(), today.Day(), 0, 0, 0, 0, time.Local)
gocron.Every(3).Hours().From(&t).Do(task)
```
For example if I run this code at 2:00 AM, I'd like that task starts at 3:00 AM, not at 5:00 AM.
Is there a method to do this?
Thanks.

**Comment by JohnRoesler** [comment]
@antoniocapizzi95 hey, this repo is no longer maintained (per the note in the readme) - we have a maintained fork over at https://github.com/go-co-op/gocron and recently added support for this exact use! https://github.com/go-co-op/gocron/issues/106

**Comment by antoniocapizzi95** [comment]
@JohnRoesler thank you very much, I will try this fork.
