### ISSUE TITLE
Do I have to use <- gocron.Start()

### ISSUE THREAD

**Issue by danhardman** [jasonlvhit/gocron#17]
I was just looking at the examples on the readme and I just wanted to clarify the purpose of `<- gocron.Start()`

If I have: 
``` go
gocron.Every(1).Second().Do(task)
```
Will that work as is? Or do I need to run `<- gocron.Start()` to initiate it?

**Comment by danhardman** [comment]
Answer is yes. 

``` go
gocron.Every(1).Second().Do(task)
```
Creates the routine

``` go
<- gocron.Start()
```
Executes the routines.

**Comment by NeutronStein** [comment]
`gocron.Start()`  starts the default scheduler and returns actually a channel `chan bool` which can be used to stop the scheduler. That channel is intended to only receive(it never returns, in this case) an input which will cause scheduler's stop. Reading from it blocks forever.
