### ISSUE TITLE
Run task just once

### ISSUE THREAD

**Issue by danhardman** [jasonlvhit/gocron#18]
Is there a idiomatic way of scheduling a task to run just once? That is to say, create a schedule that is ran once and then cleared?

The only way I can think of is:

``` go
func scheduleOnce() {
  s := gocron.NewScheduler()
  s.Every(1).Day().At("10:30").Do(foo, s)
  <- s.Start()
}

func foo(s *gocron.Scheduler) {
  // My code
  s.Clear()
}
```

Which I haven't actually tested yet but I figured this would be a solution to my problem.

**Comment by puzanov** [comment]
Seems that this tool is only for periodical tasks

**Comment by danhardman** [comment]
Seems like it from the responses... I ended up not using this tool for it and found a really good way to schedule a task to run once at a specific time.

**Comment by marksalpeter** [comment]
Thanks for the feedback @danhardman. I think we should add an easy way to schedule a task to run one time in the future. @puzanov is correct for now, gocron is just for recurring tasks.

**Comment by Sef1995** [comment]
Is this already implemented?

**Comment by whyamiroot** [comment]
Would really like to see this feature too

**Comment by danhardman** [comment]
@whyamiroot I implemented this just using the standard library I believe, I'll dig the code out later on if you like?

**Comment by whyamiroot** [comment]
@danhardman Yes, please, it would be great

**Comment by maxotov** [comment]
Hello everybody! thid feature implemented? can i use it?

**Comment by antonprokopovich** [comment]
@danhardman Would you mind sharing the code if you still have it? It would help me a great deal

**Comment by ericlentz** [comment]
Run once:

`_, _ = s.Every(1).Millisecond().LimitRunsTo(1).Do(task)`

If you inspect the scheduler after this executes the task is no longer present in the scheduler.
