### ISSUE TITLE
Run every hour at defined minute

### ISSUE THREAD

**Issue by tutunci** [jasonlvhit/gocron#2]
Hi,
looking at code and examples there is a way to do a task every day at fixed time gocron.Every(1).Day().At("10:30").Do(task)
but if I must do a task every hour at fixed minute how can do?

Thanks
Maurizio

**Comment by marksalpeter** [comment]
You would do something like this
```go
gocron.Every(38).Minutes().Do(func () {})
```
I hope that answered your question!

**Comment by itsaibk** [comment]
is it possible to achieve -> `Every(1).Hour()` at **00 min** and **00 sec**?
`---`
thanks!
