### ISSUE TITLE
Setting Timezone?

### ISSUE THREAD

**Issue by seenickcode** [jasonlvhit/gocron#22]
Is this possible?  For example, set to run a task at 12:00 UTC?

**Comment by marksalpeter** [comment]
It should be

**Comment by c0ze** [comment]
How ? (for ex, Tokyo ? GMT + 9:00)

**Comment by c0ze** [comment]
Ok, it seems there is a ChangeLoc interface available which you can pass your location.

Thanks !

https://github.com/jasonlvhit/gocron/blob/42a5804d37aa0b9239b265e894a16b8edbf52d54/gocron.go#L33

**Comment by VarunBatraIT** [comment]
```
	location, err := time.LoadLocation("Asia/Kolkata")
	if err != nil {
		log.Println("Unfortunately can't load a location")
		log.Println(err)
	} else {
		gocron.ChangeLoc(location)
	}
	
```

Works and tested!
