### ISSUE TITLE
Day of the Week not working?

### ISSUE THREAD

**Issue by lgessler** [jasonlvhit/gocron#23]
I have written a simple program that writes hello at a certain time on both Monday and Friday:

``` go
package main
import (
  "fmt"
  "github.com/jasonlvhit/gocron"
)

func main() {
  gocron.Every(1).Monday().At("15:54").Do(func() { fmt.Println("Hi from Monday!") })
  gocron.Every(1).Friday().At("15:54").Do(func() { fmt.Println("Hi from Friday!") })
  <-gocron.Start()
}

```

The output today (Friday) at 15:54 on my OS X machine was this:

```
Hi from Monday!
Hi from Friday!
```

Also, it is not relevant that the two times were the same. This

``` go
  gocron.Every(1).Monday().At("16:13").Do(func() { fmt.Println("Hi from Friday!") })
  gocron.Every(1).Friday().At("16:14").Do(func() { fmt.Println("Hi from Monday!") })
```

produced this by 16:14:

```
Hi from Friday!
Hi from Monday!
```

Any ideas?

**Comment by postromantic** [comment]
Got similar issue today with a code
`gocron.Every(1).Friday().At("12:00").Do(func() { fmt.Println("ok") })`
Today is Monday, but it's triggered
(go 1.6 x64 Windows)

**Comment by seenickcode** [comment]
I set mine to every Sunday at 12:00pm and it appears to be sending every Monday at 11:00am.  

go 1.4 Ubuntu

**Comment by philmcp** [comment]
Same problem here!

**Comment by VarunBatraIT** [comment]
Got a similar issue:
gocron.Every(1).Monday().Friday().At("12:00").Do(func() { fmt.Println("ok") })

It doesn't work on Monday but works on Friday.

**Comment by icholy** [comment]
This package totally broken ...

**Comment by whyamiroot** [comment]
Is the issue resolved now?

**Comment by whyamiroot** [comment]
Is the issue resolved now?
I had a task to run at sunday and couple of tasks ro tun at monday, but all of them were triggered at sunday

**Comment by jkc** [comment]
@whyamiroot - I believe my commit would fix the issue, but it hasn’t been reviewed or merged, so it isn’t resolved in master. You could try my fork to see if it fixes the issue for you, until this (and the other prs that are open for other issues) gets reviewed...

**Comment by jkc** [comment]
Not sure how many people are still following this long open issue, but the PR to fix it has been merged. It could be closed, assuming people can verify the fix for their own versions of the issue. Works for me now, anyway :)

**Comment by sathya0803** [comment]
`func hi() {
	fmt.Println("hi")
}
func main() {
	gocron.Every(5).Minute().Do(hi)
}`
I tried running this after importing. But my program is not giving any output. I expected it would run for every 5 mins

**Comment by JohnRoesler** [comment]
@sathya0803 this repo isn’t maintained anymore. Please checkout https://GitHub.com/go-co-op/gocron which is an active fork
