### ISSUE TITLE
Bad performance and huge CPU consumption

### ISSUE THREAD

**Issue by igor-uzhviev** [jasonlvhit/gocron#3]
Unfortunately due to constant infinite loop (in Start() function) which constantly check jobs without any delay CPU consumption of my go app is always 100%. It is the same on my Windows laptop and on a Windows server.

That is very sad because I have to run one job every hour, another job - once a day (at a certain time). All other time my application should do nothing, but it consumes 100% CPU. That makes the library completely unusable for me.

I had to switch to my custom selector with 2 timers.
Hourly timer is simple:
```
hourlyTick := time.Tick(1 * time.Hour)
```

Daily timer is a bit complicated as I have to run it at a certain time.
The code looks like that:
```
// for target daily time 20:00
now := time.Now()
targetDailyTime := time.Date(now.Year(), now.Month(), now.Day(), 20, 00, now.Second(), now.Nanosecond(), now.Location())

durationTillDailyTime := targetDailyTime.Sub(time.Now())
if durationTillDailyTime < 0 {
	durationTillDailyTime += 24 * time.Hour
}

dailyTick := time.Tick(durationTillDailyTime) // wait till exact time first time

select {
case <- dailyTick:
	// do stuff here
	dailyTick = time.Tick(24 * time.Hour)
}
```

That would be perfect if the library would be reimplemented using selectors with timers (or any other approach) so it won't consume CPU when the jobs are not running.

**Comment by gabstv** [comment]
I second this. My servers are hitting 100% cpu usage all the time since I started using gocron. I had no idea until now that I ran the profiler.
![pprof](http://i.imgur.com/A3CUmNL.png)  
I ran the profiler in a time where the usage should be pretty low.

**Comment by marksalpeter** [comment]
Thanks for the heads up @gabstv. I merged https://github.com/Claudiu/gocron into this version of the repo to add his fix. @igor-uzhviev I agree that ultimately it might be better to reimplement this with multiple tickers instead of one.
