### ISSUE TITLE
At() seems to be not working

### ISSUE THREAD

**Issue by davis12529** [jasonlvhit/gocron#36]
`gocron.Every(1).Day().At("9:00").Do(task)`

The task gets run every day at time of scheduling execution instead of every day at specified timing

**Comment by shukla2112** [comment]
@davis12529 Is this resolved? I don't see any PR, How did you solve?

**Comment by davis12529** [comment]
@shukla2112 are you facing this issue as well? Unfortunately I am currently tight in deadlines and could not take a closer look at it. I had to switch to another library.

**Comment by mkozjak** [comment]
@davis12529 Which one? Did you find it good for you?

**Comment by davis12529** [comment]
@mkozjak https://github.com/carlescere/scheduler, works well for me. 

The only downside is that you cannot pass arguments to the job within the schedule function. One of the workaround is to create an anonymous function with no parameters and call the intended function pass the parameters directly

e.g.

`task := func() {
			foo("param1", "param2")
}`

**Comment by mkozjak** [comment]
@davis12529: Yeah, been looking into that one, too. That was the downside for me to, too. I decided to just use the cron lib.

**Comment by kaiiak** [comment]
@davis12529 @mkozjak 
I think you should write this way.

```go
gocron.Every(1).Day().At("09:00").Do(task)
```
