### ISSUE TITLE
Some commits need to be reverted.

### ISSUE THREAD

**Issue by Claudiu** [jasonlvhit/gocron#5]
Hi!

Thank you for merging my fork! Please keep in mind that I changed the name of some includes, due to the fact that I saw my code as something exotic.

Here are the commits that need to be reverted:
https://github.com/jasonlvhit/gocron/commit/d2c27bcb60b407af11f2dfb69e7b130972c8840a

Also in the README file: Search and replace claudiu to jasonlvhit

Thank you again! :+1:

**Comment by marksalpeter** [comment]
Ah, i didn't catch that. I'll have time to revert those changes soon. Until then I don't think it's breaking anything essential.

**Comment by Claudiu** [comment]
Fixed with https://github.com/jasonlvhit/gocron/commit/980c96bf412b6e28177bcf6b7105640cf04137d6
