### ISSUE TITLE
Jobs start at different time

### ISSUE THREAD

**Issue by Noy** [jasonlvhit/gocron#53]
Hey, I'll try and explain this as best as possible.

Say I set a task at 09:30

`scheduler := gocron.NewScheduler()`
` scheduler.Every(1).Day().At("09:30").Do(someTask)`

Say my task takes 10 minutes to complete at 09:30 and ends at 09:40, the next day, the task starts at 9:40, and repeats this, so eventually this task will be running at a completely different time if left forever.

Not sure if you've noticed this, but i thought it would be worth mentioning.

Thanks!

**Comment by Oded** [comment]
+1

**Comment by gljubojevic** [comment]
Hi, I have created fork https://github.com/gljubojevic/gocron because of that issue and submitted pull req

**Comment by Noy** [comment]
Look good, should fix the issue. Will test this on monday

**Comment by Noy** [comment]
Update: Code works, fixes issue.

**Comment by dtelyukh** [comment]
+1

**Comment by Streppel** [comment]
This issue could be closed at this moment, right?

**Comment by arushijn** [comment]
+1

When is this fix getting merged?

**Comment by Streppel** [comment]
The merge now has conflicts with master. I'll take a look into it later and see what I can do about it.

**Comment by Streppel** [comment]
I can proudly say that this has been finally been merged! :) Many thanks to @gljubojevic for taking the time to contribute to the project.

**Comment by pycckuu** [comment]
For me, the fix did not work. I have a task that should be repeated every hour, but sometimes it just starts and runs endlessly.

**Comment by Streppel** [comment]
@pycckuu we've corrected this is [our fork](https://github.com/go-co-op/gocron) but I've just applied it in here as well, thanks for pointing it out!
