### ISSUE TITLE
The package is full of race conditions + panics

### ISSUE THREAD

**Issue by marcsantiago** [jasonlvhit/gocron#55]
If you run your test with the race flag on `go test ./... -race -v` go will flag the package with having race conditions. 

Also, panics are dangerous in production. I've forked and created a production safe version

https://github.com/marcsantiago/gocron

**Comment by mclarkson-sky** [comment]
Hi! were these race condition and panic changes merged into this repo?

**Comment by marcsantiago** [comment]
I maintain a separate fork that I use in production, but I do not believe I
ever opened up a PR against the origin

**Comment by Azuka** [comment]
@marcsantiago, do you mind opening a PR against this repo, if @jasonlvhit approves, of course?

**Comment by marcsantiago** [comment]
Sure, I can do that

**Comment by marcsantiago** [comment]
I've gone ahead and opened request at your request


Marc Anthony Santiago
Susquehanna University Class of 2013
Biology and Philosophy double major
Research Honors
Beta Beta Beta Biological Honors Society
Personal Website: http://www.marcsantiago.com/
StackOverFlow: http://stackoverflow.com/users/4639336/msanti
GitHub: https://github.com/marcsantiago

**Comment by kaiiak** [comment]
OK, I will fix this bug
