### ISSUE TITLE
I don't understand the interval part of s.Every(1).Second()

### ISSUE THREAD

**Issue by unisqu** [jasonlvhit/gocron#59]
I don't understand what's the "1" inside Every(). What does it mean? Interval of what?
s.Every(1).Second().

1. Will it memory leak?
2. When will it end? (i would like infinite loop til forever)
3. Is this below correct for maintenanceFunc to be ran exactly every day at 3:30am?
               //s.Every(1).Day().At("3:30").Do(maintenanceFunc)
4. when I put as Second, it only display in intervals of 2 (i did timestamp display using

         s := gocron.NewScheduler()
         s.Every(1).Second().Do(displayTimeStamp)
         <- s.Start()

1543144245
1543144247
1543144249
1543144251
1543144253

help

**Comment by kaiiak** [comment]
same issue [#47](https://github.com/jasonlvhit/gocron/issues/47)

**Comment by whutwxn** [comment]
same issue

**Comment by Streppel** [comment]
1 - Will it memory leak?
 I don't see the reasoning behind this, maybe a use case would help here. Just running a scheduler doesn't leak memory 

2 - When will it end? (i would like infinite loop til forever):
It's supposed to run until it receives a stop message, so it will run for as long as the hosting machine is still alive

3 - Is this below correct for maintenanceFunc to be ran exactly every day at 3:30am?
//s.Every(1).Day().At("3:30").Do(maintenanceFunc):
Yes

4 - when I put as Second, it only display in intervals of 2
This has been fixed (finally!) :)
