### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by fgblomqvist** [jasonlvhit/gocron#62]
Seems like there are a lot of issues and PRs that don't get tended to. Maybe put a notice in the README at least in case it's looking for more maintainers and/or should be considered stale?

(Worth adding: it still seems like the "best" cron/scheduler library for Go so I think it'd be worth it to keep maintaining it by allowing new maintainers onboard)

**Comment by fgblomqvist** [comment]
Gonna tag @marksalpeter here since he seems to be the last maintainer/committer

**Comment by marksalpeter** [comment]
Good idea @fgblomqvist. Thanks for reaching out.

**Comment by marksalpeter** [comment]
I also put the version we use in production at dealyze here if you want to take a look.
https://github.com/marksalpeter/gocron
