### ISSUE TITLE
Could it runs just one time ?

### ISSUE THREAD

**Issue by carmel** [jasonlvhit/gocron#66]
as the title, just like  job.at("00:00").thanks first

**Comment by kaiiak** [comment]
Can you contribute the code?

**Comment by ngethe** [comment]
@carmel what do you want to do?
I think you can use 

gocron.Every(1).Day().At("10:30").Do(task)

where 10:30 is h:m time you want to run the task

**Comment by carmel** [comment]
> @carmel what do you want to do?
> I think you can use
> 
> gocron.Every(1).Day().At("10:30").Do(task)
> 
> where 10:30 is h:m time you want to run the task

sorry for the late reply，
Not every day， just one day，thank you！

**Comment by vgichira** [comment]
@carmel You could achieve that by doing the following
gocron.Every(1).Monday().At("10:30").Do(task)

// clear the cron job

gocron.Remove(task)
gocron.Clear()

**Comment by carmel** [comment]
sorry for late reply,  I just use the time.Ticker instead，because of the simple application scenarios
