### ISSUE TITLE
s/intervel/interval

### ISSUE THREAD

**Issue by Vitucho** [jasonlvhit/gocron#67]
Just a minor thing...
https://github.com/jasonlvhit/gocron/blob/6771d4b492ba2d5f57919c04b4cddb3735365120/gocron.go#L72

BTW thanks for sharing the code!

**Comment by kaiiak** [comment]
Can you talk more?

**Comment by ngethe** [comment]
This is more of your liking between British and American English it is a word :) http://freefactfinder.com/definition/Intervel.html
