### ISSUE TITLE
Multithreaded Cron

### ISSUE THREAD

**Issue by villajo** [jasonlvhit/gocron#69]
Note: This is something that I've already forked code and am looking at the possibility of implementing. 

What I've noticed is that the cron does not run multi threaded. They each run linearly. EG: 

I have a two queries to a DB. Both should be set at the same time. But, from what I can tell, query 1 runs first, query 2 runs a short time after. Not really what I'm wanting in a scheduler. 

Ideally: 

I'd like to have as many threads as I specify to run at a time. I'd like to be able to set a limit so I don't collapse a system if I have thousands of queries.

**Comment by elvarb** [comment]
stumbled on this repo, so I havent tried this, but try just adding go in front of calling the gocron function

**Comment by iammen** [comment]
Hi, I have created fork https://github.com/iammen/gocron from https://github.com/marcsantiago/gocron because of this issue and need something more but I've not yet submitted a pull request to this repo because need more test. I holp it can help you.
