### ISSUE TITLE
Changing the Every(1).[second, minute, etc] interface

### ISSUE THREAD

**Issue by Streppel** [jasonlvhit/gocron#71]
I was thinking about changing the single time frames interface. 

So basically, it would be removing the single time frame `s.Every(1).Second().do(...)` (et al) methods, and adding a new interface like `s.EverySecond().do(...)` for single seconds, and other unit time frames. Or maybe `s.EverySecondDo(...)`.

My motivation is that informing informing a time unit for a mandatory time window seems quite redundant.

Of course this has low priority and would make breaking changes. What do you guys think about this? Any feedback?

**Comment by codingsett** [comment]
personally i think `s.Every(1).Second().do(...)` is more modular and a user doesn't have to use different code for single time frame and different code for other timeframes

**Comment by Streppel** [comment]
@codingsett those are good points. I'll be closing this issue as I've changed my mind since its opening. It's not much of an issue to keep the API as it is. Thanks for your feedback!
