### ISSUE TITLE
Need a clarification

### ISSUE THREAD

**Issue by AjithKumar-Raj** [jasonlvhit/gocron#96]
@Streppel What is equivalent to `0 * * * *` every hour cron need to run on 00 min?

**Comment by Streppel** [comment]
@AjithKumar-Raj currently, you can not do that. The best you can do to achieve something like that is to run hourly. However, this is a valid use case. I believe we will implement this soon.

**Comment by AjithKumar-Raj** [comment]
Thanks @Streppel
